### ISSUE TITLE
there is depencies here on your host machine please push what you need beside your script 

### ISSUE THREAD

**Issue by moatasemelsayed** [M-EMBABI/Embedded_Linux#1]
https://github.com/M-EMBABI/Embedded_Linux/blob/807556443d86b45826d2f61438666730e31403ec/python/GUI%20bitcoin.py#L28

**Comment by M-EMBABI** [comment]
![IMG-20230810-WA0038](https://github.com/M-EMBABI/Embedded_Linux/assets/137911793/efffcf9d-770b-47eb-988c-e7ba7883707f)
