### ISSUE TITLE
update the path 

### ISSUE THREAD

**Issue by moatasemelsayed** [M-EMBABI/Embedded_Linux#2]
https://github.com/M-EMBABI/Embedded_Linux/blob/4471336920ce3a198cf9a6cca38fb9d76db93472/python/GUI%20bitcoin/GUI%20bitcoin.py#L28

**Comment by M-EMBABI** [comment]
![IMG-20230810-WA0038](https://github.com/M-EMBABI/Embedded_Linux/assets/137911793/340bf1db-05d9-4a91-8512-f9189566a62b)

**Comment by M-EMBABI** [comment]
@moatasemelsayed 
Sorry, I think I deleted your previous comment by mistake. I modified the file and added the picture
